### ISSUE TITLE
충희에게 연락하기

### ISSUE THREAD

**Issue by ChungH** [Jin02/SOCEngine#11]
아주 중요한 이슈임미다.

**Comment by ChungH** [comment]
아니면 이슈 테러할껑미다

**Comment by ChungH** [comment]
010-7277-0851

**Comment by Jin02** [comment]
?

**Comment by ChungH** [comment]
폰 안살림?
2016. 2. 29. 오전 8:41에 "Jin Park" <notifications@github.com>님이 작성:

**Comment by ChungH** [comment]
오 라벨도 달아주셨넹

**Comment by Jin02** [comment]
ㅂㅂ 오늘 입대

**Comment by ChungH** [comment]
ㄹㅇ ?

**Comment by Jin02** [comment]
왜 안자고 있냐
일부로 자고 있을거 같아서 지금 보낸건데

2016-03-07 1:43 GMT+09:00 ChungH <notifications@github.com>:

**Comment by ChungH** [comment]
잘라고 누워있었음

폰울려서 뭔가하고봤더니 ㅇㅇ

어디로감 ?

**Comment by Jin02** [comment]
논산

**Comment by ChungH** [comment]
으ㅠㅠ
이번에야 말로 잘다녀오셈

아 전에 현서랑 잇던 방에서 군대간다고 막 얘기했던거 미안했음

몸 건강히 잘다녀오고

나도 이제 3d 공부 시작할듯
얘기할건 많은데 편지보내겟슴다
근데 주소를 알 방법이없네
2016. 3. 7. 오전 1:47에 "Jin Park" <notifications@github.com>님이 작성:

**Comment by Jin02** [comment]
ㅂㅂㅂ
그리고 잘못은 내가한건데 너가 미안해 할 필요는 없어 ㅜ

**Comment by ChungH** [comment]
너 어디에 있는지 알수있는방법좀ㅋㅋㅋㅋ

뭐 동생이나 뭐 누구한테 주소좀 나한테 보내달라고 부탁좀 하고갈수있음 ?

**Comment by Jin02** [comment]
휴가나오면 여기에 주소 적어둘게 ㅎㅎ

**Comment by ChungH** [comment]
ㅋ알았음
야 너 생일 언제냐

**Comment by Jin02** [comment]
민환형 훈육분대장이라고 했었나 --..

**Comment by ChungH** [comment]
그랬지 그 형 논산 조교
