### ISSUE TITLE
@_@

### ISSUE THREAD

**Issue by ChungH** [Jin02/SOCEngine#18]
잘 사나봄 ?
어디서 이슈를 올리는거지....
어디로 갔어 ?

**Comment by Jin02** [comment]
사지방
잘 사는거 같진 않다.

**Comment by ChungH** [comment]
왜여 
부대 어딘데 ?
지금 사지방 할수있 ?

**Comment by Jin02** [comment]
This issue was moved to TeamSOC/SOCEngine#18
