### ISSUE TITLE
Image Based Lighting & Enviroment

### ISSUE THREAD

**Issue by Jin02** [Jin02/SOCEngine#8]
Cube Mapping이라고도 불리는 그걸 구현한다.
일단 이걸 구현하는건 쉬우니 Sky 시스템도 구현한다.

**Comment by Jin02** [comment]
![wtf](http://i.imgur.com/hcKYSqB.png)

Direct Lighting 적용 후, Camera main rendertarget에 SkyBox를 입혀줬더니 이런 문제가 물체의 테두리 부분이 약간 긁혀서 나온다 -_-..

음.. GBuffer에서 같이 처리할 수 있도록 수정해봐야겠다.
그럼.. 이런 문제가 사라지지 않을까 -_-?

**Comment by Jin02** [comment]
![SkyBox](http://i.imgur.com/RRItNYD.png)

SkyBox를 GBuffer Emission으로 옮겼다.
그리고 Greater Equal Depth State 적용함.

그래도 좀 -_-; 뭔가 틈이 보이긴 하는데 AA로 대충 때워버리면 될거 같다

**Comment by Jin02** [comment]
위 2개의 사진에서 검은색으로 나오는 부분은 빛이 제대로 들어가지 않은 문제였다.
공식을 제대로 입력하지 않아 생긴 문제였는데 이젠 해결 된 상태이다.

**Comment by Jin02** [comment]
IBL의 기본 구성이나 공식은 Unreal4, 간단한 이론은 http://goo.gl/DYO51z 여기서 참고하며 구현 중

**Comment by Jin02** [comment]
![IBLPass](http://i.imgur.com/HEGuINm.png)

대충.. 된거 같기도 하고..?
Metallic, Specularity, Roughness 모두 0.5다.

**Comment by ChungH** [comment]
오 이쁘네

야 근데 왜 연락 씹고 안하는거임 ?
쌩깔꺼임 ?

**Comment by Jin02** [comment]
This issue was moved to TeamSOC/SOCEngine#8
